# Generated by Django 3.2.9 on 2021-12-01 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=320)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedureID', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureOrder',
            fields=[
                ('procedure_orderID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.appointment')),
                ('procedureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=320)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('pager_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('salary', models.PositiveIntegerField()),
                ('departmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_admin.department')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.patient'),
        ),
    ]
