# Generated by Django 3.2.8 on 2021-12-05 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default=0.0005, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
